version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: fpa_mongo  
    restart: always
    ports:
      - "2717:27017"
    networks:
      - backend_network
volumes:
  mongodb_data:
    driver: local

networks:
  backend_network:
    driver: bridge
